name: Compile and Test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  compile-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code from ${{ github.repository }}/${{ github.ref }}
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Update permissions
        working-directory: .
        run: chmod +x ./gradlew
      - name: Build and Test
        working-directory: .
        run: ./gradlew build test --info --stacktrace
