name: Publish snapshot on Maven Central

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  java-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code from ${{ github.repository }}/${{ github.ref }}
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Update permissions
        working-directory: .
        run: chmod +x ./gradlew ./.github/scripts/*.sh
      - name: Check version
        working-directory: .
        run: ./.github/scripts/check_version.sh
      - name: Build and Publish
        working-directory: .
        env:
          SIGNING_KEY_ID: ${{ secrets.OSSRH_GPG_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.OSSRH_GPG_SECRET_PASSWORD }}
          SIGNING_SECRET_KEY_RING_FILE: ~/.gradle/maven-central.gpg
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.ORG_GRADLE_PROJECT_mavenCentralUsername }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.ORG_GRADLE_PROJECT_mavenCentralPassword }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.ORG_GRADLE_PROJECT_signingInMemoryKey }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.ORG_GRADLE_PROJECT_signingInMemoryKeyId }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.ORG_GRADLE_PROJECT_signingInMemoryKeyPassword }}
          
        run: |
          ./gradlew build test publishAllPublicationsToMavenCentral --info --stacktrace
